- name: xml file for ceph-admin vm
  template:
    src: vm-template.xml.j2
    dest: /tmp/ceph-admin.xml
  vars:
    name: ceph-admin
    emulator: /usr/libexec/qemu-kvm
    qcow2Files: ["/opt/vm/ceph-admin.qcow2"]
    memory: 2097152
    vcpu: 2
    bridge: br0
    macAddress: 52:54:00:38:fd:a9

- name: define vm ceph-admin
  virt:
    name: ceph-admin
    command: define
    uri: qemu:///system
    xml: "{{ lookup('file', '/tmp/ceph-admin.xml') }}"

- name: start vm ceph-admin
  virt:
      name: ceph-admin
      state: running